### ISSUE TITLE
Little question about this library

### ISSUE THREAD

**Issue by Layri2432** [microbit-foundation/microbit-fs#19]
Sorry if my question looks idiot, but ... How exactly can I use this library ?
Thanks !

**Comment by microbit-carlos** [comment]
Hi,

Apologies for the really late reply. The documentation is not ready yet, but hopefully the quick start reference could be helpful: https://microbit-foundation.github.io/microbit-fs/quick-guide.html

In essence this a library that can be used by web-based editors to add files into a micro:bit MicroPython hex file.

You can add this project as an npm dependency, or get the ES5 bundle from the [GH Releases](https://github.com/microbit-foundation/microbit-fs/releases) page to add directly as a `<script>` tag into your web page/app.

Did that help?

**Comment by Layri2432** [comment]
Ok, thank you for the reply and for the help  !
Have a nice day !

**Comment by microbit-carlos** [comment]
I'll close this ticket as resolved, but if you have any question please do reopen it.

Thanks!
